### ISSUE TITLE
Hud elements only rendering while in clickgui or hudeditor

### ISSUE THREAD

**Issue by 0Yos** [lukflug/PanelStudio#21] opened 2021-05-08 20:04 UTC

**Comment by ChompChompDead** [comment] 2021-05-08 20:13
*No description provided.*

**Comment by Xeretis** [comment] 2021-05-08 20:13
The issue is caused by the HUDVisibility and GUIVisibility not getting toggled when you press esc to leave the gui.

A temporary solution is to toggle the GUIVisibility when the esc key is pressed and it is on. Same goes for HUDVisibility.

**Comment by IUDevman** [comment] 2021-05-08 20:18
Crucify lukflug

**Comment by yagel15637** [comment] 2021-05-08 20:26
@IUDevman kinky 😏

**Comment by IUDevman** [comment] 2021-05-08 21:13
![image](https://media.discordapp.net/attachments/781148355551952947/838852473657491476/unknown.png)

**Comment by srgantmoomoo** [comment] 2021-05-09 00:00
![image](https://user-images.githubusercontent.com/69589624/117556530-f846a000-b037-11eb-816c-3b9fb262f6ed.png)

**Comment by srgantmoomoo** [comment] 2021-05-09 00:01
u have to call the `render()` method in an event so that its constantly rendered.

**Comment by Xeretis** [comment] 2021-05-09 04:59
In order for the render method to actually run, both HUDVisibility and GUIVisibility has to be false, but that only happens once when you load up the game, because the instant you turn either the hud editor or the clickgui on, one of them gets turned on and never turned off again.

(This is 0.2 on the latest commit, i use mc16fabric but it might not be an issue on other mc versions since the MinecraftHUDGUI is different)

**Comment by lukflug** [comment] 2021-05-09 06:24
Ok, so I found the issue: PanelStudio-MC16 uses the default Minecraft behavior for the escape key, instead of `exitGUI`.

**Comment by lukflug** [comment] 2021-05-09 07:40
Fixed in c32868b

**Closed as completed by lukflug** 2021-05-09 07:40 UTC
